name: next-terminal Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  next-terminal_Release:
    name: next-terminal release
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Private Actions Checkout
        uses: actions/checkout@v3
      - name: node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: |
          cd web
          npm install --global yarn
          yarn
      - name: go Setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build package Linux
        run: |
          sh build.sh
          mv next-terminal next-terminal-bin
          mkdir next-terminal
          cp next-terminal-bin next-terminal/next-terminal
          cp config.yml.example next-terminal/config.yml
          cp LICENSE next-terminal/
          tar zcvf next-terminal.tar.gz next-terminal/
      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: next-terminal.tar.gz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}